
package time_log;

import java.awt.Frame;
import java.awt.Point;


public class ErrorSaveFrame extends javax.swing.JFrame {

    String error_str;
    ViewProjectFrame project_stage;
    Time_log time_stage;
    ConfigureFrame config_frame;
    /**
     * Creates new form Error_stage
     * @param error_str
     * @param project_stage
     * @param time_stage
     */
    public ErrorSaveFrame(String error_str, ViewProjectFrame project_stage, Time_log time_stage) {
        this.project_stage=project_stage;
        this.time_stage=time_stage;
        initComponents();
        setFrameLocation(project_stage, this);
        this.error_str=error_str;
        error_label.setText(error_str);
    }
    
    public ErrorSaveFrame(String error_str, ConfigureFrame config_frame, Time_log time_stage){
        initComponents();
        this.config_frame=config_frame;
        this.time_stage=time_stage;
        setFrameLocation(config_frame, this);
        this.error_str=error_str;
        error_label.setText(error_str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error_label = new javax.swing.JLabel();
        yes_btn = new javax.swing.JButton();
        no_btn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ERROR");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error_label.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_label.setText("jLabel1");
        getContentPane().add(error_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 57));

        yes_btn.setBackground(new java.awt.Color(51, 255, 51));
        yes_btn.setFont(new java.awt.Font("Elephant", 1, 16)); // NOI18N
        yes_btn.setText("YES");
        yes_btn.setBorderPainted(false);
        yes_btn.setFocusPainted(false);
        yes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_btnActionPerformed(evt);
            }
        });
        getContentPane().add(yes_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, 40));

        no_btn.setBackground(new java.awt.Color(51, 255, 51));
        no_btn.setFont(new java.awt.Font("Elephant", 1, 16)); // NOI18N
        no_btn.setText("NO");
        no_btn.setBorderPainted(false);
        no_btn.setPreferredSize(new java.awt.Dimension(69, 29));
        no_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_btnActionPerformed(evt);
            }
        });
        getContentPane().add(no_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 100, 40));

        background.setBackground(new java.awt.Color(255, 51, 0));
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_btnActionPerformed
        if(project_stage!=null){
            project_stage.setToDefault();
            this.dispose();
            project_stage.dispose();
            time_stage.setVisible(true);
        }
        else{
            this.dispose();
            config_frame.dispose();
            time_stage.setVisible(true);
        }
    }//GEN-LAST:event_yes_btnActionPerformed

    private void no_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_btnActionPerformed
        this.dispose();
    }//GEN-LAST:event_no_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorSaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorSaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorSaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorSaveFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    private void setFrameLocation(Frame frame_value_from, Frame frame_to_set){
        Point location_on_screen=frame_value_from.getLocationOnScreen();
        location_on_screen.setLocation(location_on_screen.getX()-(frame_to_set.getWidth()-frame_value_from.getWidth())/2, location_on_screen.getY()+(frame_value_from.getHeight()-frame_to_set.getHeight())/2);
        frame_to_set.setLocation(location_on_screen);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel error_label;
    private javax.swing.JButton no_btn;
    private javax.swing.JButton yes_btn;
    // End of variables declaration//GEN-END:variables
}
